<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promises and observable learning</title>
</head>
<body>
    <h2>JavaScript Promise</h2>
    <p id="d1"></p>
    <p id="d2"></p>
<hr>

    <script>
        function myfun(some) {
            document.getElementById("d1").innerHTML = some;
        }

        let myPromise = new Promise(function(myResolve, myReject) {
            let x = "0";

            if (x == 0) {
                console.log("Everything is alright");
            } else {
                console.log("Some Error");
            }
        });

        function myfun2(some1) {
            document.getElementById("d2").innerHTML = some1;
        }

        let myPromise1 = new Promise(function(Resolve, Reject) {
            let y = "1";

            if (y === 1) {
             console.log("Everything is alright");
            } else {
               console.log("Some Error");
            }
        });


        myPromise.then(
        function(value) {myfun(value);},
        function(error) {myfun(error);}
        );
        myPromise1.then(
        (value) => myfun2(value),
        (error) => myfun2(error),
        );
        

        var p1 = Promise.resolve(3);
        var p2 = 1337;
        var p3 = new Promise((resolve, reject) => {
        setTimeout(() => {
                resolve("foo");
            }, 100);
            });

        Promise.all([p1, p2, p3]).then(values => {
        console.log(values);
});


        var p = Promise.resolve([4,2,3]);
        p.then(function(v) {
        console.log(v[0],v[1], v[2]); 
        });

        var p4 = new Promise(function(resolve, reject) {
            resolve('Success');
            });

            p4.then(function(value) {
            console.log(value); 
            throw new Error('oh, no!');
            }).catch(function(e) {
            console.error(e.message); 
            }).then(function(){
            console.log('after a catch the chain is restored');
            }, function () {
            console.log('Not fired due to the catch');
            });

        
            p4.then(function(value) {
            console.log(value); 
            return Promise.reject('oh, no!');
            }).catch(function(e) {
            console.error(e); 
            }).then(function(){
            console.log('after a catch the chain is restored');
            }, function () {
            console.log('Not fired due to the catch');
            });


    </script>
</body>
</html>